### PR TITLE
First version of Dockerfile

### LINKED ISSUE #205: [Feature Request] Docker image for CI/CD
**Is your feature request related to a problem? Please describe.**
Many CI/CDs use docker to run pipelines.

**Describe the solution you'd like**
It'd be nice to have a ready-to-use docker image to use in a CI/CD environment, to install a specific version of Flutter and to execute some unit/integration tests, using **fvm**.

### PR DESCRIPTION
**Pull request by andreadelfante**
Hi guys,

I created a very-first version of a docker image for a ready-to-use fvm environment for based-docker CI. 

I didn't edit the Github actions to build the image and to publish it on Docker Hub, because I have no clue about the release workflow.
If you give me more info about it I can give you my support!

Closes #205 

Cheers! :beers:

### CODE REVIEW

**Comment by leoafarias** [comment]
Thanks @andreadelfante. Regarding the actions can you provide a new workflow that does the deploy to the docker hub. With that I can configure as part of the release workflow.

**Comment by andreadelfante** [comment]
Perfect! Just a question:

> Thanks @andreadelfante. Regarding the actions can you provide a new workflow that does the deploy to the docker hub. With that I can configure as part of the release workflow.

Ok then!
In your opinion, is it good to have a single Dockerfile with a variable `version` (passed in Docker build command, maybe?)? Or is it better to have multiple Dockerfiles for each fvm version?

**Comment by leoafarias** [comment]
I am not as familiar with docker config, but I believe the latest version of the image should use the latest version of fvm.

**Comment by andreadelfante** [comment]
Sorry, i cannot edit the Actions from my fork.

I paste here `.github/workflows/cli_deploy_docker.yml` 
```
name: Create Docker Release

on:
  workflow_dispatch:

jobs:
  deploy-docker:
    name: Docker Deploy (latest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (latest)
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          file: ./.docker/Dockerfile
          push: true
          tags: leoafarias/fvm:latest

  deploy-docker-latest:
    name: Docker Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1


      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./.docker/Dockerfile
          push: true
          tags: leoafarias/fvm:${{ github.event.release.tag_name }}
          build-args: FVM_VERSION=${{ github.event.release.tag_name }}
```

**Comment by AngeloAvv** [comment]
Are there any updates?

**Comment by leoafarias** [comment]
@all-contributors please add @andreadelfante for idea, code

**Pull request merged**
