### PR TITLE
Fix isGlobalConfigured()

### LINKED ISSUE #248: [BUG] New global command
@leoafarias Hello! I'm trying out the new prerelease version for fvm on Linux, in particular the new `global` command.
I think I have the PATH correctly configured but fvm it's giving me the new warning:

image

Maybe the issue is that `which` is taking into account the binary name?
Something like changing the equals to:  
```dart
path.join(kGlobalFlutterPath, 'flutter') == await which('flutter') 
```  

```dart
  static Future<bool> isGlobalConfigured() async {
    /// Return false if link does not exist
    if (!await kGlobalFlutterLink.exists()) return false;
    return kGlobalFlutterPath == await which('flutter');
  }
```

### PR DESCRIPTION
**Pull request by davidmartos96**
Fixes #248

### CODE REVIEW

**Comment by davidmartos96** [comment]
:thinking: The test run fine on my Linux desktop...

**Comment by davidmartos96** [comment]
Well.. Indeed it fails. The CI is not aware of the PATH env :sweat_smile: 
Let me know if we should remove the check inside the test or if you know of a way to test it.

**Comment by davidmartos96** [comment]
But how would we set the PATH from inside the test? `Platform.environment` is an unmodifiable map.
https://api.dart.dev/stable/2.12.2/dart-io/Platform/environment.html

**Comment by leoafarias** [comment]
I can add it on test suite later. Go ahead and remove this test, I have to implement tests on a per service.

**Comment by davidmartos96** [comment]
@leoafarias Just found a way to do it using the environment parameter of `process_run`. 
Here is the diff:

image

**Comment by leoafarias** [comment]
great I have a helper already that injects this. Just have to see how to implement it without having to pass the environment variable.  On that function

**Pull request merged**
