### PR TITLE
Fix a error for projectFlutterLink.

### PR DESCRIPTION
**Pull request by CaiJingLong**
The judgment condition of the root directory is wrong.

### CODE REVIEW

**Comment by CaiJingLong** [comment]
The CI report error. But the console all tests passed.

And I can't locate the error.

image

**Comment by leoafarias** [comment]
I have no idea what's going on with Github actions. The last few runs have been stuck for the past 5 hours and I had to cancel. Seems to get stuck on the List command test. I rewrote the whole logic to check for installed versions because I thought the issue was a future that does not return. What I think it's weird is that the test does not timeout which I have set for 5 minutes.

**Comment by leoafarias** [comment]
@CaiJingLong I was able to fix the issue. It was caused by the projectFlutterLink method which was causing an infinite loop. 

I changed it into a recursive function and set a limit of levels to look up on. I might look later how to make sure it meets a root level conditional
https://github.com/leoafarias/fvm/commit/b499e52f438831f9c7b8e58f87f344989a331149

**Comment by leoafarias** [comment]
@CaiJingLong because of the changes to this, I suggest taking a look to see if the problem persists on your end. If so you can open the PR again

Thanks!

**Comment by CaiJingLong** [comment]
@leoafarias 


> @CaiJingLong I was able to fix the issue. It was caused by the projectFlutterLink method which was causing an infinite loop.
> 
> I changed it into a recursive function and set a limit of levels to look up on. I might look later how to make sure it meets a root level conditional

This is also my doubt, this PR itself is submitted to solve this problem.
But anyway, as long as you can fix the problem.

**Pull request closed without merging**
