### PR TITLE
Improve fvm flutter

### PR DESCRIPTION
**Pull request by jascodes**
Working on #73

### CODE REVIEW

**Comment by orestesgaolin** [comment]
Hi there! Please let me put my 2 cents.

Even though it may seem more convenient to override `flutter` I think it's better to be completely aware/transparent if the fvm binary is being called. There are several ways to achieve similar behavior (e.g. `alias flutter="fvm flutter"` or any other alias). If such option would be possible, then imho it shouldn't be default as it is a "breaking" change in current behavior. 

I enjoy `fvm` for its convenience and how much it improves my dev speed, but I think there should be some clear _distinction_ between fvm and _official/recommended_ flutter setup.

**Comment by jascodes** [comment]
@orestesgaolin `fvm alias` and `fvm alias --remove` will be used for explicit aliasing. This was just to start dicussion with @leoafarias

**Comment by jascodes** [comment]
@leoafarias You can pull this.. Aliasing can be left to user as you wanted earlier. Feel free to make any changes.

**Comment by leoafarias** [comment]
@jascodes would like to write some tests for this piece. If you can't get to it I will try to add it over the weekend.

**Comment by jascodes** [comment]
@leoafarias Let's see if I can beat you to that 😃

**Comment by leoafarias** [comment]
> @leoafarias Let's see if I can beat you to that 😃

Please do!

**Comment by leoafarias** [comment]
@jascodes bringing this in

**Comment by jascodes** [comment]
@leoafarias I though tests were needed in this? I didn't have time to look into them though..

**Comment by leoafarias** [comment]
@jascodes I am working on tests that is why

**Comment by jascodes** [comment]
@leoafarias Cool, thx 👍

**Pull request merged**
