### PR TITLE
Fix terminal stdin

### PR DESCRIPTION
**Pull request by leoafarias**

### CODE REVIEW

**Comment by leoafarias** [comment]
closes #160

**Comment by lyio** [comment]
Oh thank you for fixing the terminal stdin. I kept getting a `StdinException` when using fvm together with Fastlane and could not figure out at all what was going wrong.

**Comment by kuhnroyal** [comment]
Still getting it with 1.3.3 :(
This is inside an SSH session, not sure it has something to do with it.
```
[2020-10-14T23:55:20.745Z] + fvm --verbose install
[2020-10-14T23:55:21.686Z] Version: 1.22.1 - already installed.
[2020-10-14T23:55:21.686Z] [     0.513s] StdinException: Error setting terminal echo mode, OS Error: Operation not supported by device, errno = 19
[2020-10-14T23:55:21.686Z] Internal Error: Could not finish setting up Flutter sdk
[2020-10-14T23:55:21.686Z] #0      flutterSetupWorkflow (package:fvm/src/workflows/flutter_setup.workflow.dart:11:5)
[2020-10-14T23:55:21.686Z] <asynchronous suspension>
[2020-10-14T23:55:21.686Z] #1      InstallCommand.run (package:fvm/src/commands/install_command.dart:51:13)
[2020-10-14T23:55:21.686Z] <asynchronous suspension>
[2020-10-14T23:55:21.686Z] #2      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
```

**Comment by leoafarias** [comment]
I just think this is a bug in dart... might have to remove the echoMode.. as the api is very inconsistent.

**Comment by kuhnroyal** [comment]
I have pinned fvm to 1.2.3 for now in CI, didn't get it to work with any 1.3.x

**Comment by kuhnroyal** [comment]
Might be related: https://github.com/dart-lang/sdk/issues/34213
Or maybe this can help from the APK utils in Flutter: https://github.com/flutter/flutter/pull/42892/files

**Comment by kuhnroyal** [comment]
Also having a problem on my local machine. I am using fastlane and call fvm from there, now with 1.3.3 the fastlane commands don't terminated after the fvm commands finish.

**Comment by leoafarias** [comment]
@kuhnroyal could you provide me the snippet on fastlane so I could try to replicate?

**Comment by kuhnroyal** [comment]
Add this to a project in `$PROJECT/fastlane/Fastfile`
```
lane :fvmtest do
  Dir.chdir "#{ENV["project_root"]}" do
    sh("fvm flutter doctor")
  end
end
```

Run with `fastlane fvmtest` or ` bundle exec fastlane fvmtest` depending on how you installed fastlane.
`fvm flutter doctor` succeeds but the process doesn't terminate.

**Pull request merged**
