### PR TITLE
global flutter >  which flutter

### PR DESCRIPTION
**Pull request by YangLang116**

### CODE REVIEW

**Comment by leoafarias** [comment]
@YangLang116 can you explain a bit the motivation behind this change?

**Comment by YangLang116** [comment]
> @YangLang116 can you explain a bit the motivation behind this change?

1、There's no need to specify a "PATH"
2、’which flutter‘ means default flutter path。However, When calling ’fvm flutter ...‘ command, should try to use the version maintained by FVM

**Comment by leoafarias** [comment]
@all-contributors please add @YangLang116 for code

**Comment by leoafarias** [comment]
@YangLang116 I had to make some changes but will bring this functionality manually. Will keep this open until I bring it in.

**Pull request merged**
