### PR TITLE
Users can configure to use unofficial git sources.

### PR DESCRIPTION
**Pull request by CaiJingLong**
Such as: 
```bash
fvm config -r https://gitee.com/kikt/flutter.git
```

And, If user use unofficial git sources, the console will print:

```bash
$ fvm install 1.13.5
Downloading 1.13.5...
The flutter remote is https://gitee.com/kikt/flutter.git. This is not an official source, you need to confirm the security yourself.
```

### CODE REVIEW

**Comment by CaiJingLong** [comment]
@leoafarias The CI system look like have no permission to get code.
I think you need check the CI config.

**Comment by leoafarias** [comment]
@CaiJingLong will check it out thanks!

**Comment by leoafarias** [comment]
@CaiJingLong So this is interesting.. it seems like its a limitation on GitHub Actions. https://github.community/t5/GitHub-Actions/Github-Workflow-not-running-from-pull-request-from-forked/td-p/32979/highlight/true/page/3

Can you check your options under actions, to see if there is anything on your end that you need to enable?

**Comment by leoafarias** [comment]
I removed the analysis step out of the PR workflow until they address this issue.

**Comment by leoafarias** [comment]
@CaiJingLong do you mind sharing a bit more about the reason for this and what is the usage?

**Comment by CaiJingLong** [comment]
As the flutter warehouse grows, the clone speed will become slower and slower.
The speed of accessing github in China is not ideal. Sometimes the clone speed is less than 100k, and fvm install <version> takes more than 10 minutes. 

The flutter team also has source for [pub in China](https://flutter.dev/community/china), but git remote does not.

As a distributed system, git can set its own remote, as long as the user is confident that the remote is safe. 

Therefore, in order to facilitate some users who are slow to clone on github, we can add this feature to allow users to set their own remote url.

**Comment by leoafarias** [comment]
I might wait to merge this... I am have been thinking about a refactor that needs to be done on the way we are pulling the flutter versions and might address some confusion on the way the versions get stored. I will create a PR for this and bring that in.

**Comment by CaiJingLong** [comment]
I think pull should add `--depth = 1` param to the git pull command, even delete the .git folder after clone.

**Comment by leoafarias** [comment]
> I think pull should add `--depth = 1` param to the git pull command, even delete the .git folder after clone.

I think this is a great suggestion however there is some weird behavior when doing the --depth=1, it causes the Flutter version and channel to return as `0.0.0-unknown` and channel also as `unknown` which I know it breaks the flutter upgrade but I am concerned it might have some other consequences from the tooling.

**Comment by CaiJingLong** [comment]
> > I think pull should add `--depth = 1` param to the git pull command, even delete the .git folder after clone.
> 
> I think this is a great suggestion however there is some weird behavior when doing the --depth=1, it causes the Flutter version and channel to return as `0.0.0-unknown` and channel also as `unknown` which I know it breaks the flutter upgrade but I am concerned it might have some other consequences from the tooling.
> 
> [flutter/flutter#32684](https://github.com/flutter/flutter/issues/32684)

Yes, this is a problem, so we should do it carefully.
However, since fvm was originally used for version management of flutter, then user should also use fvm when upgrading.

**Comment by leoafarias** [comment]
Did you test for backwards compatibility. The other versions have the “v” I front of it.

Seems that this would have an issue on older versions. Can you confirm?

**Comment by CaiJingLong** [comment]
Sorry, I forget the PR.
I'll close it.

If you think need add "unofficial git source" function for the library, I will open a separate branch and reopen a pull request.

The function of the About 'v' prefix, because I only use it myself, does not guarantee forward compatibility. The old version of v.1.15.0 requires the following migration :

| old | new |
| - | - |
| 1.15.0 | v1.15.0 | 

Regarding the issue of the v prefix, because there has been no time to do too much extra coding work recently, it is temporarily impossible to turn on PR.

**Comment by leoafarias** [comment]
Same here, will take the time to review this change they have made.

**Pull request closed without merging**
