### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by leoafarias**
#52

### CODE REVIEW

**Comment by kuhnroyal** [comment]
@leoafarias The version property in `src/version.dart` was not updated in the release

**Comment by leoafarias** [comment]
@kuhnroyal did you commit them the changes. Not sure what happened especially since it passed the tests. Could you do another PR?

**Comment by kuhnroyal** [comment]
I am not sure how this works, it says it is generated.

**Comment by kuhnroyal** [comment]
Looks like you added a builder for that but it did not get generated before the release.

**Comment by leoafarias** [comment]
OK I got it now.. its a manual process that needs to be done I will be automating. Funny thing is that it was deployed with 0.7.0 even though is 0.7.1, will make some adjustments to automate some of these things

**Comment by leoafarias** [comment]
@kuhnroyal thanks for helping me out with this

**Pull request merged**
