### PR TITLE
Fix macOS errors

### LINKED ISSUE #210: The app doesn't build on macOS
**Describe the bug**
The current version of fvm doesn't build on macOS.

**To Reproduce**
1. Clone the repo
2. run `flutter run` on macOS

**Expected behavior**
The app should run on macOS

**Desktop (please complete the following information):**
 - OS: macOS 11.1 Big Sur (intel)
 - FVM Version 1.3.7 

**Additional context**
The file_chooser repo doesn't contains anymore a pubspec.yaml

### PR DESCRIPTION
**Pull request by nank1ro**
I fixed the issue using the pub.dev dependency of `file_chooser`.

I also fixed a crash on the ExploreScreen

Then I also resolved some warnings.

closes  #210

### CODE REVIEW

**Comment by leoafarias** [comment]
@nank1ro thanks for the PR, I had a branch with some of the improvements on #175. I will review the conflicts between them as the GUI improvements as a lot of changes.

**Review by leoafarias — APPROVED** [review]

**Comment by leoafarias** [comment]
@all-contributors please add @nank1ro  for code

**Comment by nank1ro** [comment]
Thank you for adding me as a contributor, I really appreciate it! 🎉
When I have time, I would be pleased to contribute again.

**Comment by leoafarias** [comment]
@nank1ro that would be great! Thanks again!

**Pull request merged**
