### PR TITLE
feat: automatically add `~/.fvm_flutter/bin` to the PATH var in `install.sh` and introduce `update.sh`

### PR DESCRIPTION
**Pull request by Nidal-Bakir**
This will fix: #699

### CODE REVIEW

**Comment by SSebigo** [comment]
Is it good ? This is the only problem I have with FVM right now.

**Comment by Nidal-Bakir** [comment]
@SSebigo 
Yes

**Comment by vicenterusso** [comment]
That script did work for me, fresh fedora40 install

```
ln: failed to create symbolic link '/home/vicente/.local/bin/fvm': No such file or directory
error: Failed to create symlink.
``` 

There is no `.local/bin/` yet. should the script handle this, maybe?

**Comment by toddtail** [comment]
> @SSebigo Yes, you can use this updated script to install FVM on Linux. This will probably not get merged now, so you can copy and paste the updated script to your machine, make it executable, and run it.

The Script worked for me but still got 2 things needs to be done manually:

1. create bin folder in ~/.local
2. add `export PATH="$PATH:$HOME/.local/bin/"` to .bashrc file

**Comment by Nidal-Bakir** [comment]
@leoafarias 

>can we maybe move the directory to ~/.fvm/bin/fvm instead of local, and make both mac and linux consistent?

I cannot speak for the Mac because I do not have a Mac, and I do not know if Mac has a `./local/bin` folder or if this folder is a standard thing in the Mac world. The `./local/bin` is a conventional thing in the Linux world, and it is fair to assume that the developer who is **_bashing a script of the internet_** already has `./local/bin` in his `PATH` variable.

Nonetheless, we can add some extra comments to note that the `./local/bin` needs to be in the `PATH` variable, and you need to create such a folder if none exists.

**Comment by vicenterusso** [comment]
> it is fair to assume that the developer who is **_bashing a script of the internet_** already has `./local/bin` in his `PATH` variable.

Lets agree to disagree. You are correct. Most users should already have `./local/bin` in his `PATH` variable. In my specific case, FVM was my first install after a fresh fedora install. I quickly fixed adding to the PATH and creating the `./local/bin` folder.

But it shouldn't hurt having these small checks inside the script, makes it more reliable.

**Comment by Nidal-Bakir** [comment]
We can make the script create the `./local/bin` folder `mkdir -p ./local/bin`, but how can we add the `PATH="$PATH:$HOME/.local/bin/` to `.bashrc` or `.zshrc` ... ETC. I'm not aware of a solution for that :/

**Comment by vicenterusso** [comment]
> We can make the script create the `./local/bin` folder `mkdir -p $HOME/local/bin`, but how can we add the `PATH="$PATH:$HOME/.local/bin/` to `.bashrc` or `.zshrc` ... ETC. I'm not aware of a solution for that :/

That's trivial to add to PATH but personally I would just echo the instructions to the user add manually

**Comment by Nidal-Bakir** [comment]
>That's trivial to add to PATH but personally I would just echo the instructions to the user add manually

No, it's not trivial!

- We can not use `echo` in this situation we do not know where the `.bashrc`/`.zshrc`.... files are!
- Each time the user runs the script, the script will `echo` the instructions to the user `.bashrc`/`.zshrc` assuming we know the path of these files.

**Comment by Nidal-Bakir** [comment]
So as for now, it turns out that some distros do not follow the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

> User-specific executable files may be stored in $HOME/.local/bin. Distributions should ensure this directory shows up in the UNIX $PATH environment variable, at an appropriate place.

We need to do the following:
 
1. Create the $HOME/.local/bin folder if it does not exist. We can easily do that using `mkdir -p $HOME/.local/bin`.
2. Instruct the user to add `$HOME/.local/bin/` to their PATH variable if it does not already exist.

**Comment by vicenterusso** [comment]
> > That's trivial to add to PATH but personally I would just echo the instructions to the user add manually
> 
> No, it's not trivial!
> 
> * We can not use `echo` in this situation we do not know where the `.bashrc`/`.zshrc`.... files are!
> * Each time the user runs the script, the script will `echo` the instructions to the user `.bashrc`/`.zshrc` assuming we know the path of these files.

Jesus, man. when I say "echo" I mean display it to terminal to the user add it manually. But yes, its trivial to automatically add to correct shell file and still check if ts already set.

**Comment by Nidal-Bakir** [comment]
So we have two options I think:

1.  Instruct the user to add $HOME/.local/bin/ to their PATH variable if it does not already exist using `echo` as an output of running the script. And I would add this to the website also just to be more clear for all the users
2. if @vicenterusso has a script to add this the user PATH var

**Comment by leoafarias** [comment]
@Nidal-Bakir When looking at similar .sh scripts to install, I found the use of `.packagename` over `.local`. For example, if you look at the install.sh for Bun on https://bun.sh, which you can find here: https://bun.sh/install, it seems the same behavior is for Mac and Linux and does use local.

Can you take a brief look at this, as it would be more straightforward to just set this?

**Comment by leoafarias** [comment]
@Nidal-Bakir, can you confirm my message above with the example from Bun? It seems they are not using local. I would prefer this approach if it works without manual intervention.

**Comment by Nidal-Bakir** [comment]
Hi @leoafarias sorry for the delay. I am currently only available during weekends (Friday for me) I will get this done by tomorrow.
I believe I can make it seamless for the user.

**Comment by Nidal-Bakir** [comment]
@leoafarias 

I appreciate your feedback and I believe everything is in good shape. However, I wanted to note one thing: I have added an update script. Users should use this update script to update FVM. Otherwise, the install script **_may_** repeatedly add the FVM bin path to the PATH variable. While this isn't harmful, it's not ideal.

There’s no way to be certain that FVM is fully added to the PATH, because we are checking the local PATH per the SHELL variable. This means that FVM might be in the PATH for zsh or fish, but not for bash. Since we are piping the script to bash, we can only see the PATH for the bash scope. This is why I have included the update.sh script.

**Comment by BriceCroix** [comment]
Hi. I encountered the same problem trying to install fvm on ubuntu. I can use the script provided in this PR, but is there any update about it ? Is there a reason not to merge it for now ?
Thanks !

**Comment by leoafarias** [comment]
I am bringing this in, but most likely will have to do a full review across all the platforms.

**Pull request merged**
